# Generated by Django 4.2.23 on 2025-07-31 13:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lendings_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lending',
            unique_together={('user', 'book')},
        ),
    ]
